title: "Can LLMs Help You at Work? 
    A Sandbox for Evaluating LLM Agents in Enterprise Environments"
description: "A comprehensive framework for evaluating Large Language Model agents within realistic enterprise environments"
url: "https://ast-fri.github.io"
baseurl: "/EnterpriseBench"

theme: jekyll-theme-minimal
markdown: kramdown

# Optional: Add your custom CSS
plugins:
  - jekyll-seo-tag